[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/image-proxy"
  to = "/.netlify/functions/image-proxy"
  status = 200

[functions."image-proxy"]
included_files = ["netlify/functions/image-proxy/images/**"]
